displayName=Slayer Helper
author=HSJ
description=Slayer helper plugin to assist with point boosting and tureal/aya skipping
tags=combat,slayer,helper,turael,aya,mazchna,krystilia,points
version=1.0
plugins=hsj.external.slayerhelper.SlayerHelperPlugin
build=standard